[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && java -Dserver.port=$PORT -jar target/coming-soon-backend-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixpkgsArchive = "e05605ec414618eab4a7a6aea8b38f6fbbcc8f08"